#ifndef _CCSPRITEPLUS_H_
#define _CCSPRITEPLUS_H_

#include "cocos2d.h"

/* autogenerated, fill with whatever you need */

class CCSpritePlus : public cocos2d::CCSprite
{
public:
    CCSpritePlus();
    virtual ~CCSpritePlus();
};

#endif  // _CCSPRITEPLUS_H_
