#ifndef _CHECKPOINTOBJECT_H_
#define _CHECKPOINTOBJECT_H_

#include "cocos2d.h"

/* autogenerated, fill with whatever you need */

class CheckpointObject : public cocos2d::CCNode
{
public:
    CheckpointObject();
    virtual ~CheckpointObject();
};

#endif  // _CHECKPOINTOBJECT_H_
