#ifndef _ENDPORTALOBJECT_H_
#define _ENDPORTALOBJECT_H_

#include "cocos2d.h"
#include "gj/GameObject.h"

/* autogenerated, fill with whatever you need */

class EndPortalObject : public GameObject
{
public:
    EndPortalObject();
    virtual ~EndPortalObject();
};

#endif  // _ENDPORTALOBJECT_H_
