import traceback

INCLUDE_BASE = ["cocos2d"]

H_TEMPLATE = """
#ifndef DEFNAME
#define DEFNAME

HEADERS

/* autogenerated, fill with whatever you need */

class CLASSNAMEINHERIT
{
public:
    CLASSNAME();
    virtual ~CLASSNAME();
};

#endif  // DEFNAME
"""[1:]

CPP_TEMPLATE = """
#include "CLASSNAME.h"

/* autogenerated, fill with whatever you need */

CLASSNAME() { }
virtual ~CLASSNAME() { }
"""[1:]

def gen_files(classname, inherit=None, extra_headers=None):
    include = INCLUDE_BASE[:]
    if extra_headers is not None:
        include += extra_headers
    
    defname = f"_{classname.upper()}_H_"
    headers = "\n".join(f'#include "{x}.h"' for x in include)
    
    cpp = CPP_TEMPLATE.replace("CLASSNAME", classname)
    h = H_TEMPLATE.replace("CLASSNAME", classname)
    h = h.replace("DEFNAME", defname)
    h = h.replace("HEADERS", headers)
    if inherit is not None:
        h = h.replace("INHERIT", f" : public {inherit}")
    else:
        h = h.replace("INHERIT", "")
    
    return (cpp, h)

if __name__ == "__main__":
    try:
        classname = input("classname: ")
        inherit = input("inherit: ")
        if not inherit:
            inherit = None
        header = input("header: ")
        if header:
            headers = [header]
        else:
            headers = None
        cpp, h = gen_files(classname, inherit, headers)
        
        with open(f"{classname}.cpp", "w") as f:
            f.write(cpp)
        
        with open(f"{classname}.h", "w") as f:
            f.write(h)
        
    except Exception:
        traceback.print_exc()
    input("now fuck off")
    
    
