#ifndef _GAMESOUNDMANAGER_H_
#define _GAMESOUNDMANAGER_H_

#include "cocos2d.h"

/* autogenerated, fill with whatever you need */

class GameSoundManager : public cocos2d::CCNode
{
public:
    GameSoundManager();
    virtual ~GameSoundManager();
};

#endif  // _GAMESOUNDMANAGER_H_
