#ifndef _GAMEOBJECT_H_
#define _GAMEOBJECT_H_

#include "cocos2d.h"
#include "gj/CCSpritePlus.h"

/* autogenerated, fill with whatever you need */

class GameObject : public CCSpritePlus
{
public:
    GameObject();
    virtual ~GameObject();
};

#endif  // _GAMEOBJECT_H_
