#ifndef _PAUSELAYER_H_
#define _PAUSELAYER_H_

#include "cocos2d.h"

/* autogenerated, fill with whatever you need */

class PauseLayer : public cocos2d::CCBlockLayer
{
public:
    PauseLayer();
    virtual ~PauseLayer();
};

#endif  // _PAUSELAYER_H_
