#ifndef _PLAYLAYER_H_
#define _PLAYLAYER_H_

#include "cocos2d.h"

/* autogenerated, fill with whatever you need */

class PlayLayer : public cocos2d::CCLayer
{
public:
    PlayLayer();
    virtual ~PlayLayer();
};

#endif  // _PLAYLAYER_H_
