#ifndef _PLAYEROBJECT_H_
#define _PLAYEROBJECT_H_

#include "cocos2d.h"
#include "gj/GameObject.h"

/* autogenerated, fill with whatever you need */

class PlayerObject : public GameObject
{
public:
    PlayerObject();
    virtual ~PlayerObject();
};

#endif  // _PLAYEROBJECT_H_
