#ifndef _PLAYERCHECKPOINT_H_
#define _PLAYERCHECKPOINT_H_

#include "cocos2d.h"

/* autogenerated, fill with whatever you need */

class PlayerCheckpoint : public cocos2d::CCNode
{
public:
    PlayerCheckpoint();
    virtual ~PlayerCheckpoint();
};

#endif  // _PLAYERCHECKPOINT_H_
