#ifndef _RINGOBJECT_H_
#define _RINGOBJECT_H_

#include "cocos2d.h"
#include "gj/GameObject.h"

/* autogenerated, fill with whatever you need */

class RingObject : public GameObject
{
public:
    RingObject();
    virtual ~RingObject();
};

#endif  // _RINGOBJECT_H_
