#ifndef _SONGOBJECT_H_
#define _SONGOBJECT_H_

#include "cocos2d.h"

/* autogenerated, fill with whatever you need */

class SongObject : public cocos2d::CCObject
{
public:
    SongObject();
    virtual ~SongObject();
};

#endif  // _SONGOBJECT_H_
