#ifndef _SPEEDOBJECT_H_
#define _SPEEDOBJECT_H_

#include "cocos2d.h"

/* autogenerated, fill with whatever you need */

class SpeedObject : public cocos2d::CCObject
{
public:
    SpeedObject();
    virtual ~SpeedObject();
};

#endif  // _SPEEDOBJECT_H_
