#ifndef _STARTPOSOBJECT_H_
#define _STARTPOSOBJECT_H_

#include "cocos2d.h"
#include "gj/GameObject.h"

/* autogenerated, fill with whatever you need */

class StartPosObject : public GameObject
{
public:
    StartPosObject();
    virtual ~StartPosObject();
};

#endif  // _STARTPOSOBJECT_H_
